### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by OneHappyForever** [misakanetwork2018/v2ray_api#1]
你好，

很期待WIKI写完。 想知道怎么用。 我主要是用MYSQL，可以用这个连接起来吗？

怎么做？

**Comment by misakanetwork2018** [comment]
您好，
感谢您关注这个项目。
目前这个版本还是一个被动调用的接口，即由数据存储端定时访问由本程序开放的HTTP RESTAPI来获取数据。不过未来会提供更多的数据同步方式，譬如直接连接远端MySQL，或者由本程序访问远端网站API。
本人表达能力较弱，请多多谅解。

P.S. Wiki将会在MySQL同步方式开发完成后更新
