### ISSUE TITLE
重新整理的构建指南

### ISSUE THREAD

**Issue by nkeonkeo** [misakanetwork2018/v2ray_api#3]
## 准备

克隆到`$GOPATH/src/v2ray-api`

(将代码中的`v2ray_api`改为`v2ray-api`,如果有的话)

进入仓库所在文件夹

运行下发代码以安装所需依赖

```bash
git clone https://github.com/v2fly/v2ray-core/ ../v2ray.com/core
go get github.com/pires/go-proxyproto
go get github.com/seiflotfy/cuckoofilter
go get github.com/akkuman/parseConfig
go get github.com/gin-gonic/gin
```

(github慢什么的请先自行挂代理)

## 构建

进入`main`文件夹

运行`go build main.go`,生成可执行文件`main`

构建完毕

## 小问题

`action/addUser.go`中的`UUID := c.PostForm("email")`请自行修改为`UUID := c.PostForm("uuid")`，否则email与uuid相同

**Comment by misakanetwork2018** [comment]
感谢提供完整构建指南
小问题的部分已经修复
（其实fork改了以后可以pull request的
（嫌麻烦就算了
